-- Users Table
CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  avatar_url VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Settings Table
CREATE TABLE settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  storage_used INT NOT NULL,
  total_storage INT NOT NULL,
  user_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Files_Data Table
CREATE TABLE files_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  files_id INT NOT NULL,
  user_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (files_id) REFERENCES files(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Files Table
CREATE TABLE files (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  size VARCHAR(255) NOT NULL,
  path VARCHAR(255),
  is_favorite BOOL,
  is_deleted BOOL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Actions Table
CREATE TABLE actions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);

-- Files_Actions Table
CREATE TABLE files_actions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  file_id INT NOT NULL,
  action_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (file_id) REFERENCES files(id),
  FOREIGN KEY (action_id) REFERENCES actions(id)
);

-- Files_Tags Table
CREATE TABLE files_tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  files_id INT NOT NULL,
  tags_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (files_id) REFERENCES files(id),
  FOREIGN KEY (tags_id) REFERENCES tags(id)
);

-- Activities Table
CREATE TABLE activities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  activity VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  files_id INT NOT NULL,
  FOREIGN KEY (files_id) REFERENCES files(id)
);

-- Comments Table
CREATE TABLE comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  comment VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  files_id INT NOT NULL,
  user_id INT NOT NULL,
  FOREIGN KEY (files_id) REFERENCES files(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Tags Table
CREATE TABLE tags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tag VARCHAR(255) NOT NULL,
  user_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);
